### ISSUE TITLE
Add options to sort bookmarks

### ISSUE THREAD

**Issue by kasbah** [Bristol-Braille/canute-ui#100]
Add options to sort bookmarks by

- [ ] Order of addition (default)
- [ ] Order of page number

Changing the option will go directly to the bookmarks afterwards.

**Comment by kasbah** [comment]
I am re-considering this one. @pachpict, do we really need two ordering systems for bookmarks? Seems to add complexity for no good reason. Just ordering by page number would make the most sense to me.

**Comment by steph-sergeant** [comment]
I agree. 


Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----

**Comment by pachpict** [comment]
I agree as well.
