### ISSUE TITLE
Better story for UI and firmware upgrades

### ISSUE THREAD

**Issue by kasbah** [Bristol-Braille/canute-ui#102]
UI upgrades as we have currently implemented them have several issues:

- No new Python packages can be introduced
- No new system packages or updates can be introduced
- The user has to perform updates

I think we need a more thought out solution. [Mender.io](https://docs.mender.io/1.1/getting-started/what-is-mender) looks like an interesting candidate (though possibly over-engineered?). Mender requires building images with Yocto I believe. [ThingOS](https://github.com/ccrisan/thingos/wiki/Firmware-Updates) could be a Buildroot based solution.

**Comment by pachpict** [comment]
The second version sent out for the Mk13s will be the first use-in-anger of the new updating system. So we'll see how smoothly that goes.
