### ISSUE TITLE
Replace library from USB stick 

### ISSUE THREAD

**Issue by kasbah** [Bristol-Braille/canute-ui#11]
Currently If a USB stick is present when the Canute is booted up it loads new PEF (and BRF) files from it into the library. There is no way to remove files from the library.

For the Mk10;

Does not automatically load books from USB sticks on boot up or any other time.
Instead replace "Refresh Library" option in the System Menu with "Replace Library from USB Stick".
This checks if their are any PEF or BRF files on the USB stick.
If there are none then do nothing (play negative noise on motors?)
If there is then it deletes all the current library,
then loads all PEF and BRF books into the library, as with previous behaviour.

This is designed to make the Canute suitable for multiple users in public environments. Users should be told in manual to keep a copy of all their files on a USB stick, not just on the Canute.

-- Edited by pachpict

**Comment by mattvenn** [comment]
no auto loading is most likely due to missing udev rules
