### ISSUE TITLE
Sort library into alphabetical order

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#136]
Currently does not seem to be always in alphabetical order. Have not observed properly to say what the current order is. Issue based on feedback from Steph.

**Comment by kasbah** [comment]
It's _definitely_ in alphabetical order in the version on the master branch. Mk12 needs to be updated. We can re-open this if it remains an issue then.

**Comment by kasbah** [comment]
To elaborate: I have been working on #98 so soon we will have two options for the sorting order.
