### ISSUE TITLE
Punctuation is in computer braille

### ISSUE THREAD

**Issue by kasbah** [Bristol-Braille/canute-ui#140]
Should be UEB like the numbers.

**Comment by pachpict** [comment]
Correct fix for this in menu labels and help text is to complete issue #145 , and let various transcriptions be made.

This does not solve the file names being in computer Braille, but that is less of an issue as we have no intention of using contractions in file names in any case, and the punctuation is not usually important. Computer Braille is probably fine for file names; at least until we receive complaints the the contrary.
