### ISSUE TITLE
System menu says its page one of two, but its only one page.

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#154]
Behaviour observed in March at CSUN, not looked for it since...

**Comment by kasbah** [comment]
Page number display code was changed since then so it's unlikely that this is still current behaviour.

**Comment by kasbah** [comment]
Oops, nevermind. It does still seem to be doing that.

**Comment by steph-sergeant** [comment]
Hi Josh, 

 

Room for further development if it still has 2 pages. 

 

Are you going to put the sort books into latest read first? 

Makes a difference with a large library. 

 

Have a good weekend.

Steph 

 

Stephanie Sergeant 

 

Vision Through Sound CIC

Tel: 0121 445 2161 

Mobile:  07793 906 745 

Email:  <mailto:Stephanie@screenreader.net> Stephanie@screenreader.net 

Website:  <http://www.visionthroughsound.co.uk/> http://www.visionthroughsound.co.uk

**Comment by kasbah** [comment]
Hi Steph, who is Josh?  Latest read first would make sense but that's a separate issue. I'll look into this one.

**Comment by Lazarus404** [comment]
Any further thoughts on this PR?

**Comment by kasbah** [comment]
You are commenting on the issue, not a pull-request. The pull-request you opened for this issue is #161 where I asked you to review my changes. I have requested reviews through the github interface for other pull-requests as well which I don't think you noticed.

**Comment by Lazarus404** [comment]
Hey Kaspar,

Yes, I noticed.  I acted on several of the items but haven't had chance 
to complete them all, yet.  I will be tidying it up and rounding it off 
tomorrow, most probably.

I didn't notice posts on the other PR's.  I'll check on them once 145 is 
squared away.

Lee
