### ISSUE TITLE
Can we ignore FAT hidden files?

### ISSUE THREAD

**Issue by kasbah** [Bristol-Braille/canute-ui#176]

**Comment by pachpict** [comment]
Yes, we should ignore all *nix (starting with a dot) and FAT style hidden files and folders. This is important as users will not expect them to appear in their Canute libraries.

**Comment by pachpict** [comment]
Is this implemented?

**Comment by zwbrbr** [comment]
Unix and Mac things beginning with dot are ignored.

FAT and exFAT are not, currently, except for the special case of the medium's recycle bin.

FAT attributes aren't trivially exposed.  There's a low-level ioctl we could use though; see https://stackoverflow.com/a/15896112
