### ISSUE TITLE
HDMI output to show print version of the same BRF book

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#188]
Required for US Quota distribution. Requested by UK QTVIs.

The HDMI output is to show a print version of the same file. 

In an ideal world this would be an element within PEF XML files (a print page node which is linked to or a child of each Braille page node).

In our world this is easier done as follows;

 - Looks for a 'print file' with the same name but a special extension, e.g. "book.brf.specialextension" and print the same nine lines to the HDMI as are on the Canute display. Trust that whoever authors the print file will match the lines up, and it is there look-out if they didn't.

 - If "book.brf.specialextension" doesn't exist then print "book.brf" to the HDMI out, thus showing raw BRF, which is better than nothing and often quite readable, even for those unfamiliar with BRF.

 - In theory the same should be extended to PEF. But one thing at a time. Lets do it for BRF first and see how it goes.

**Comment by zwbrbr** [comment]
Note that the incarnation in `aph-hdmi-output` currently supports only display of the BRF, not finding/displaying sidecar files.
