### ISSUE TITLE
Progress and success indicated during upgrade

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#189]
This was a comment from Jasone Fayre of the CNIB, from Mk13 testing. It was unclear whether the Canute had successfully been upgraded when he followed the correct proceedure. Ideally this improvement would be in place for the initial launch (i.e. for pilot programmes), hence being marked for the initial milestone. However it isn't the end of the world if it isn't; it will just cause require greater support labour from BBT and our distributors for the next upgrade if it isn't.

**Comment by zwbrbr** [comment]
Fixed in `b1848e6` and `390c801` in `pi-misc` on Gitlab.
