### ISSUE TITLE
Allow Canute to be controlled as a display again

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#203]
Allow Canute to  be controlled as a display through the USB-B port, especially by screen readers such as NVDA. (Note that this was previously supported by the Canute UI and support was built into a build of Chrome OS, but has been subsequently disabled due to changes to the UI and in the underlying hardware.)

**Comment by zwbrbr** [comment]
Making this dependent upon [firmware issue #17](https://gitlab.com/Bristol-Braille/canute-firmware/issues/17) because we don't want to spread/inflict the protocol sync/async inconsistency wider than necessary.

**Comment by zwbrbr** [comment]
Making this dependent upon [firmware issue #17](https://gitlab.com/Bristol-Braille/canute-firmware/issues/17) because we don't want to spread/inflict the protocol sync/async inconsistency wider than necessary.

**Comment by zwbrbr** [comment]
USB was re-enabled as of `pi-misc` `90a936a`.  Protocol could certainly be improved, but we *could* ship it as-is.

**Comment by zwbrbr** [comment]
Next step: try using UI natively with external Canute on USB, just to see.

**Comment by zwbrbr** [comment]
UI runs with an external Canute, which is good enough for now.  Can raise separate bugs for protocol concerns, albeit against Gitlab firmware repo rather than here.
