### ISSUE TITLE
Make it obvious Canute is alive whilst booting

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#209]

**Comment by zwbrbr** [comment]
Strong interaction with a discussion today about warm-up and errors; let's assume that a totally cold machine can't guarantee 100% fidelity, and therefore attempt to just perform ongoing tactile activity for as long as possible while warming up, before doing a reset once warm, then relinquishing control to the UI.

**Comment by pachpict** [comment]
Happy with current implementation of this. No doubt we'll get a lot of feedback about this soon after launch.
