### ISSUE TITLE
Reader should be able to delete a bookmark

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#212]
Can we already do this? Forgive me if I should know the answer to this, as I've forgotten. @kasbah and @zwbrbr your input welcome. Note to self: this is in reference to APH Redmine issue 5596.

**Comment by zwbrbr** [comment]
@pachpict From the code (not tried it) a long-press on a bookmark deletes it; this seems to have escaped documentation.

**Comment by zwbrbr** [comment]
Long-press works, and is documented in the context help on the APH units; they must just have missed it.  There's a [note](https://github.com/Bristol-Braille/canute-ui/commit/564e49d105586376362292466d43b3e4a8a83035#diff-f8836d55d69518a8d2f51c13010c5b06L14) to ensure it stays in the context help.

@pachpict I guess you can close Redmine 5596 with this info?

**Comment by zwbrbr** [comment]
@liamsmyth92 Per my comment May 8th, when Ed and I reviewed your context help updates in May we [made a review note to you](https://github.com/Bristol-Braille/canute-ui/commit/564e49d105586376362292466d43b3e4a8a83035#diff-f8836d55d69518a8d2f51c13010c5b06L14) pointing out that you'd dropped the bookmark deletion method, among the other suggested fixes.  I didn't re-check your amended text when you re-sent it; I just assumed that you'd addressed all problems we'd raised.

Simply revise [the existing text](https://github.com/Bristol-Braille/canute-ui/blob/master/ui/bookmarks/help.py#L8) and get your revised version to me, and I'll pop in for the next release.

**Comment by liamsmyth92** [comment]
Sent to you, added the delete bookmarks text back in.
