### ISSUE TITLE
Consider keypad factory reset

### ISSUE THREAD

**Issue by zwbrbr** [Bristol-Braille/canute-ui#215]
Liam suggests that if menus have been put in a language the user doesn't understand then it's hard to navigate to the language menu to restore the default language.  One can imagine a classroom full of kids entertaining themselves with this quite quickly.  Deleting the state file from the SD would effectively factory-reset, but is cumbersome if there are many Canutes to do this way (ideally they'd all be shut down first, etc.).  So the suggestion is some sort of magic key combination to trigger either language reset or "factory reset", howsoever we define that.

There's also the question of whether the default language, i.e. the target for a reset, should vary depending on the market into which the Canute is sold.

**Comment by pachpict** [comment]
I think its too complex for the reason your describe: we have to encode a different default language into different territories, whereas without this the distributor just needs to ship it with an SD card containing the correct state file.

So I'm going to close this and open another issue about adding information about the state file to the manual, so people know how to delete it safely.
