### ISSUE TITLE
Review help text

### ISSUE THREAD

**Issue by zwbrbr** [Bristol-Braille/canute-ui#216]
Ed to review Liam's help text as agreed.  Existing changes, linked below, has been committed but I can make a new branch to integrate feedback from this.  Pink went away, green is new.  You could use "insert a quote" in here for revisions and/or use the diff-commenting feature on each diff page (hover over a line and click the blue "+" that appears in the left margin).  Liam will likely want to know about the changes to keep the manual/device help consistent.

Hitting help while reading book text:

  https://github.com/Bristol-Braille/canute-ui/commit/551a42319358a544ba760ee4c0afd5e7f901401d#diff-57697917704b5cb220961d6b98400b4dL22

Within the main menu (context didn't exist before):

https://github.com/Bristol-Braille/canute-ui/commit/551a42319358a544ba760ee4c0afd5e7f901401d#diff-57697917704b5cb220961d6b98400b4dL36

Library menu:

https://github.com/Bristol-Braille/canute-ui/commit/551a42319358a544ba760ee4c0afd5e7f901401d#diff-e68c8cec4e0a5b214ff37fc2400e4d4dL8

Bookmarks menu:

https://github.com/Bristol-Braille/canute-ui/commit/564e49d105586376362292466d43b3e4a8a83035#diff-f8836d55d69518a8d2f51c13010c5b06L8

Go to page:

https://github.com/Bristol-Braille/canute-ui/commit/564e49d105586376362292466d43b3e4a8a83035#diff-178694a1dfb9f87d152acdc868bb0582L7

System menu:

https://github.com/Bristol-Braille/canute-ui/commit/564e49d105586376362292466d43b3e4a8a83035#diff-058f54917f47ec45fad4a7b960423065L7

Language menu:

https://github.com/Bristol-Braille/canute-ui/commit/0647f83bb6b15ef87bfabb9bb94a1cac51a6683f#diff-38fb8f5feb2558bd5ceb429179b77fc8L7

**Comment by pachpict** [comment]
Can we close this issue? (No doubt we'll need to open a new one for changing the help text at some point of course.)
