### ISSUE TITLE
Language selection reverts after hot USB swap

### ISSUE THREAD

**Issue by liamsmyth92** [Bristol-Braille/canute-ui#223]
After selecting a new language (i.e. English Grade 2) the UI reverts to default (Eng. grade 1) after hot-swapping USB stick.

**Comment by liamsmyth92** [comment]
It seems that every time Canute is turned off it reverts to default language after re-start

**Comment by zwbrbr** [comment]
[This test](https://github.com/Bristol-Braille/canute-ui/blob/00b1af9cdc60d8f6f40d0ed366ad4aa3075556f5/ui/initial_state.py#L150) was only noticing if we'd changed the current book, not that we'd changed the current language, so it wouldn't save the language until/unless the user also then changed to a new book.

**Comment by zwbrbr** [comment]
Confirm as fixed then close.

**Comment by zwbrbr** [comment]
Works on at least 1.3.11, closing.
