### ISSUE TITLE
Tailored (burn?) test firmware

### ISSUE THREAD

**Issue by zwbrbr** [Bristol-Braille/canute-ui#229]
To speed up location of errors, and to try to elicit more errors.  
This is just to track https://gitlab.com/Bristol-Braille/canute-firmware/issues/18

**Comment by pachpict** [comment]
Have set this to the first-consumer-release milestone as it will be most needed at the end of the first consumer batch release, before they are sent out.

**Comment by zwbrbr** [comment]
Customised firmware was created in Gitlab as a `canute-firmware` branch called `assemblyware`.
