### ISSUE TITLE
Update UI (and firmware?) from USB stick as System Menu command/s

### ISSUE THREAD

**Issue by kasbah** [Bristol-Braille/canute-ui#29]
Possibly firmware as well.

**Comment by pachpict** [comment]
Labelled bug as well as feature, as UI updating was present before recent change to book loading.

**Comment by kasbah** [comment]
Implemented with https://github.com/Bristol-Braille/canute-ui/commit/9f2d1772a91aba30b9f95452f02241d982f686b4.
