### ISSUE TITLE
Cannot currently load files whilst in emulated hardware mode

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#30]
Possible solution:

Draw source files from USB stick into sub-directory in UI dir, convert files in sub-dir, then delete all file from sub-dir...

1. Would look for USB stick; if found copy to this sub-dir.
2. Regardless of whether USB stick found then look in sub-dir ('/temp_sources/'?) for files and do conversion from there to usual directory for Canute-format files.
3. Regardless of whether any conversion done, delete all files in /temp_sources/.

This way a user using emulation could drop files into /temp_sources/ as though it were a USB stick and wouldn't need different modes for emulated and real hardware.

**Comment by kasbah** [comment]
I think this is possible already. It definitely will be after merging #27.  You simply need to configure the right folders in [ui/config.rc](https://github.com/Bristol-Braille/canute-ui/blob/master/ui/config.rc)
