### ISSUE TITLE
Launch firmware upgrades from the system menu

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#306]
Problem: 

We used to have the Canute only install an upgrade if it was higher than the existing installed version. However there are all sorts of times when this isn't what you want. You may want to reinstall the current version; you may be a developer messing with version numbers; you may want to downgrade.

That is why we switched to always installing the upgrade if it is on the card. But the issue with that is that the user has to manually take the card out after the upgrade, put in PC, remove the upgrade files (whilst leaving any books), then reinsert to avoid reinstalling the upgrade every time. 

Solution:

Change the Canute start-up so by default it doesn't look for upgrades. Instead add an option to the system menu to install the upgrade. Presumably the easiest way of doing that will be to have a flag set to ignore upgrades on start-up, have the menu option flip that flag then trigger a restart, then flip the flag back to ignore on first boot.

**Comment by woodcoder** [comment]
Fixed by #307
