### ISSUE TITLE
Wait longer for after crash on communications failure

### ISSUE THREAD

**Issue by kasbah** [Bristol-Braille/canute-ui#35]
To give firmware enough time for the warm-up routine

**Comment by mattvenn** [comment]
added a new section to the config file:

[comms]
timeout = 10000 # seconds

if not found, defaults to 60 as before

**Comment by kasbah** [comment]
10000 **seconds**?

**Comment by kasbah** [comment]
I think the idea was to:

- crash on comms failure
- wait a few seconds
- try again

so that it doesn't clutter up the logs when it is waiting for the arduino on start-up

**Comment by mattvenn** [comment]
any number. If the issue is just waiting for the thing to start up then find that time add 5 seconds to it and use that in the config.
