### ISSUE TITLE
Apps and Games?

### ISSUE THREAD

**Issue by moocow1452** [Bristol-Braille/canute-ui#4]
Hi. I'm not entirely sure of the scope of the Canute project, but since the device is powered by a Raspberry Pi,  could apps along side the eBook reader be officially developed and supported, or is that not part of the roadmap for now? I assume since everything appears to be Python, other uses for the Braille display outside of the Reader could be hacked in, but I didn't know what is officially supported, if such a distinction exists.

**Comment by mattvenn** [comment]
Yes that would be good. We'd like the platform to be hackable...

On 27 March 2016 at 21:16, moocow1452 <notifications@github.com> wrote:

> Hi. I'm not entirely sure of the scope of the Canute project, but since
> the device is powered by a Raspberry Pi, could apps along side the eBook
> reader be officially developed and supported, or is that not part of the
> roadmap for now? I assume since everything appears to be Python, other uses
> for the Braille display outside of the Reader could be hacked in, but I
> didn't know what is officially supported, if such a distinction exists.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Bristol-Braille/canute-ui/issues/4>
>



-- 
Matthew Venn
web mattvenn.net twitter @matthewvenn <https://twitter.com/matthewvenn>

**Comment by kasbah** [comment]
To clarify: it's not on our roadmap to add official support, we are focusing on essentials for now. We like the idea though. If someone contributed code in this direction we certainly wouldn't turn them away.
