### ISSUE TITLE
Log is too verbose: causes very slow start up under some circumstances

### ISSUE THREAD

**Issue by o0Mouse0o** [Bristol-Braille/canute-ui#40]
When loading roughly twenty books took over ten mins, assumed was broken. Stopped, checked SD card and found had generated 2.5MiB on log file, mostly "padding line" entries.

**Comment by kasbah** [comment]
The log may too verbose but it won't affect the speed very much. The book converting just takes a long time on the Pi.  "padding line" still doesn't really need to be logged.

**Comment by o0Mouse0o** [comment]
The more annoying result is that the log is soooooooooooooo long it is 
next to useless as a debugging aid.
