### ISSUE TITLE
Email Clients (Alpine) and other Text based software

### ISSUE THREAD

**Issue by ArmanArbab** [Bristol-Braille/canute-ui#5]
I don't know whether there was any plan to include internet connectivity capability as part of canute's features, whether by way of wifi or ethernet, but I thought an idea perhaps worth exploring was making use of software with primarily text based UIs from the 80s and 90s, such as the email client Alpine. Hopefully, such software could readily be converted into a braille accessible format without the use of screen readers by creating a map of characters to their corresponding braille cells.

**Comment by ArmanArbab** [comment]
I think that this better goes under issue #4 Apps and Games?

**Comment by kasbah** [comment]
I think the best route for most of these features would be to add Canute support to [BRLTTY](http://mielke.cc/brltty/).

**Comment by ArmanArbab** [comment]
wow, that looks cool. So BRLTTY would run on top of the linux kernel in the raspberry pi?

**Comment by kasbah** [comment]
Yes, or we could provide USB access to the Canute and people could use it as a BRLTTY terminal for their own computer.
