### ISSUE TITLE
Include support for BRF as well as PEF

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#7]
We've had a long standing commitment to allow BRF to be used as an input format, as PEF already is.

This should be relatively simple to add into the system as BRF represents Braille characters with ASCII, whereas PEF uses unicode Braille symbols. Therefore the two can be switched between with a regex.

The Canute Mk10 will be going out to schools to use at the end of this month. These schools generate BRF as standard rather than PEF. So if we can get this in the UI before the 23rd of September we can load the new firmware onto these Mk10 units, which will be useful for the schools' testing programmes.

It doesn't matter whether BRF is converted to PEF in the process or treated as an equal.

The format: http://www.duxburysystems.com/documentation/dbt11.1/brf_files.htm

Example BRF file in 32x8 format: http://bristolbraille.co.uk/articles/iceb_2016_designing_canute_with_the_blind_community.brf

**Comment by mattvenn** [comment]
added and new test added
