### ISSUE TITLE
Library doesn't update until after the machine has been turned off and on again

### ISSUE THREAD

**Issue by pachpict** [Bristol-Braille/canute-ui#76]
Process followed (tried repeatedly with different book selections);

 1. Loaded chosen books onto USB stick (selection different from those already on the Canute).

 2. Inserted USB stick, navigated to "System Menu" and selected "Replace Library..."

 3. No feedback, as expected (but we should add some!)

 4. Navigated back to "Library Menu", but book selection unchanged.

 5. Try 1--4 a few more times, without different results.

 5. Restarted machine and "Library Menu" has the new book selection as expected.

Ed

**Comment by kasbah** [comment]
I believe this was fixed, though I lost track of where.
