### ISSUE TITLE
Home menu

### ISSUE THREAD

**Issue by cz1392** [Bristol-Braille/canute-ui#78]
- [ ] Long press forward and backwards buttons to go 5 pages forward or backwards. 

Accessing the Home menu:
- [x] Press menu button (central button from the front buttons)
- [x] Press menu button again, it goes back to the current book.

Side button bindings:
- [x] 1 - name of the current book and current location
- [x] 2 - Go to page (Specifications are shown in #79 )
- [x] 3 - Go to start of the book
- [x] 4 - Go to the end of the book
- [x] 5 - Insert Bookmark for current page’.
- [x] 6 - Go to Bookmark
- [x] 8 - Go to library menu
- [x] 9 - Go to system menu

**Comment by kasbah** [comment]
So line 7 is just blank and no binding?

**Comment by kasbah** [comment]
Why would someone want to go to the end of a book?

**Comment by kasbah** [comment]
Why would someone want to go to the end of a book?

**Comment by steph-sergeant** [comment]
Because they are looking for information that they know is near the end of the book. 


Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----

**Comment by kasbah** [comment]
But surely that's quite a rare case and doesn't warrant it's own menu option. They can easily go to a specific page number, including the last page, using the go to page system.

**Comment by steph-sergeant** [comment]
Yes, that is true, 
We did put that in, when we were not sure if you could do page numbers.
Now you can, perhaps we can leave it out. 


Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----

**Comment by steph-sergeant** [comment]
Hi Kaspar, 

I have been talking to another Braille reader, and End of book would be useful to her too. 

This is quite a common command in the other Braille note takers, and is far quicker and easier to use than the go to page. 
I would like to add it to chen's questionnaire please. 



Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----

**Comment by kasbah** [comment]
Ok, I will implement it. It's not very hard to add, it just struck me as odd.

**Comment by steph-sergeant** [comment]
You are a star. 



Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----

**Comment by kasbah** [comment]
I changed some of the wording slightly, hope that's ok:

1. go to page
1. go to start of book
1. go to end of book
1. insert bookmark at current page
1. choose from existing bookmarks
1. 
1. view library menu
1. view system menu


Otherwise this is all done with merging of #96

**Comment by kasbah** [comment]
>I agree mostly with what you have done.
>The fact that you have changed the numbering, means I will need to change several help menus.

Sorry, the numbering actually hasn't changed. We still have the book title with page number as the first line and the rest are offset, as before. I only changed the wording a bit. 
>
>How about we put the literal
>'home menu' centralised on the top line, then we can move everything down one number, and I will not need to change the sequencing.
>I agree it is meaningless to have a title of a book on the top line, as this is a Home menu, like a central one.
>To have its name makes it so much easier to identify when directing people by phone.

I think we should leave the book title with page number as it is.  It's the only place to easily see which book you are reading and what page you are on. We do have one spare line so we could put HOME MENU above that.

**Comment by steph-sergeant** [comment]
Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----
From: Stephanie Sergeant [mailto:stephanie@screenreader.net] 
Sent: 09 August 2017 12:49
To: Kaspar Emanuel (kaspar.bumke@gmail.com)
Subject: FW: [Bristol-Braille/canute-ui] Help menu (#84)

From subsequent emails, looks like you have done some more of these menus. 

 

 

Stephanie Sergeant 

Director

 

Vision Through Sound CIC

Tel: 0121 445 2161 

Mobile:  07793 906 745 

Email: Stephanie@screenreader.net 

Website: http://www.visionthroughsound.co.uk

**Comment by steph-sergeant** [comment]
Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----
From: Stephanie Sergeant [mailto:stephanie@screenreader.net] 
Sent: 09 August 2017 12:48
To: Kaspar Emanuel (kaspar.bumke@gmail.com)
Subject: FW: [Bristol-Braille/canute-ui] Help menu (#84)

Where are you picking up the text from? 

 

I have written help text in Seafiles ui design, documents starting with ‘help’.  

 

The menu button now has the word menu on it, rather than just M. 

 

Yes, possibly your snappier text is better. Sometimes though when people are stuck, they need things spelt out. 

 

 

Stephanie Sergeant 

Director

 

Vision Through Sound CIC

Tel: 0121 445 2161 

Mobile:  07793 906 745 

Email: Stephanie@screenreader.net 

Website: http://www.visionthroughsound.co.uk

**Comment by steph-sergeant** [comment]
Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----
From: Stephanie Sergeant [mailto:stephanie@screenreader.net] 
Sent: 09 August 2017 12:38
To: Kaspar Emanuel (kaspar.bumke@gmail.com)
Subject: FW: [Bristol-Braille/canute-ui] Home menu (#78)

Ok, I will update the home menu in Seafile u.i. design. 

 

 

Stephanie Sergeant 

Director

 

Vision Through Sound CIC

Tel: 0121 445 2161 

Mobile:  07793 906 745 

Email: Stephanie@screenreader.net 

Website: http://www.visionthroughsound.co.uk

**Comment by steph-sergeant** [comment]
Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----
From: Stephanie Sergeant [mailto:stephanie@screenreader.net] 
Sent: 09 August 2017 12:36
To: Kaspar Emanuel (kaspar.bumke@gmail.com)
Subject: FW: [Bristol-Braille/canute-ui] User Guide (#83)

Most of this is already written, I need to finish it and convert to BRF. 

 

 

Stephanie Sergeant 

Director

 

Vision Through Sound CIC

Tel: 0121 445 2161 

Mobile:  07793 906 745 

Email: Stephanie@screenreader.net 

Website: http://www.visionthroughsound.co.uk

**Comment by steph-sergeant** [comment]
Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----
From: Stephanie Sergeant [mailto:stephanie@screenreader.net] 
Sent: 09 August 2017 12:33
To: Kaspar Emanuel (kaspar.bumke@gmail.com)
Subject: FW: [Bristol-Braille/canute-ui] Confirmation menu/s, waiting screens and distinguishing selectable lines (#24)

If you give me more detail, I will try and enlighten you.

 

 

Stephanie Sergeant 

Director

 

Vision Through Sound CIC

Tel: 0121 445 2161 

Mobile:  07793 906 745 

Email: Stephanie@screenreader.net 

Website: http://www.visionthroughsound.co.uk

**Comment by steph-sergeant** [comment]
Stephanie Sergeant 
Director

Vision Through Sound CIC
Tel: 0121 445 2161 
Mobile:  07793 906 745 
Email: Stephanie@screenreader.net 
Website: http://www.visionthroughsound.co.uk


-----Original Message-----
From: Stephanie Sergeant [mailto:stephanie@screenreader.net] 
Sent: 09 August 2017 12:30
To: Kaspar Emanuel (kaspar.bumke@gmail.com)
Subject: FW: [Bristol-Braille/canute-ui] Developer menu (#101)

Brilliant idea, go for it. 

 

I agree no point in having the serial number at the beginning of the book, title more important.

 

Are you implementing help text? Looks like it from the emails. 

If so, I do not need to print out 10 copies of all the help menus. 

 

Please let me know if they will be displayed on the MK 12 for Thursday. 

 

Thanks Steph 

  

 

Stephanie Sergeant 

Director

 

Vision Through Sound CIC

Tel: 0121 445 2161 

Mobile:  07793 906 745 

Email: Stephanie@screenreader.net 

Website: http://www.visionthroughsound.co.uk
