### ISSUE TITLE
Go to page

### ISSUE THREAD

**Issue by cz1392** [Bristol-Braille/canute-ui#79]
N.B. The page number is shown as Canute page number rather than BRF page number. 

If Button 2 in home menu is pressed, goes to ‘Go to page menu’
- 1 - Enter page number using the side buttons
- 2 - \<book title\> \<page number\>
- 3 - Go to page number __ /total
- 4 - Please confirm by pressing forward
- 5 - Delete character by pressing back 
- 6 - To go back to book press middle button

Page numbering is up to page 9999. If the user enters eg 14 then this is treated the same as entering 014, i.e page 14. N.B. at 

PS. Likely problem: May confuse readers. 
Possible solution: put BRF page number as an option in system menu

**Comment by kasbah** [comment]
>‘Enter page number from the sidebar to go to the desired page number
Is 67 characters and won't fit on one line with direct transcription.

**Comment by kasbah** [comment]
This has been implemented with #93.
