### ISSUE TITLE
System menu

### ISSUE THREAD

**Issue by cz1392** [Bristol-Braille/canute-ui#81]
System proposal

- [ ] 1 - Shut down

- [ ] 2 - Sorting method for book order in library menu by alphabetical order.
  It will go to the library menu with this selected method. 

- [ ] 3 - Sorting method for book order in library menu by recent read.
  It will go to the library menu with this selected method. 

- [ ] 4 - Sorting method for bookmark order by page order.
  It will go to the bookmark for a current book with this selected method.

- [ ] 5 - Sorting method for bookmark order by recent add
  It will go to the bookmark for a current book with this selected method.

**Comment by kasbah** [comment]
Closing this in favor of more specific issues #98 and #100.
