### ISSUE TITLE
Allow for bigger jumps within book

### ISSUE THREAD

**Issue by kasbah** [Bristol-Braille/canute-ui#9]
Especially to return to start. Would also be good to jump forward/back say, 10 pages. 

Use the first 3 page buttons:
1. Back to start
2. Back x pages
3. Forward x pages 

Chapters is a whole nother problem due to not all formats supporting it.

**Comment by pachpict** [comment]
Start with x=ten, until feedback gives us an informed opinion on the best number.

**Comment by kasbah** [comment]
Did we lose this feature Matt?
